language: node_js
node_js:
- "15"
os: linux

env:
  - ROOT_DIRECTORY=$TRAVIS_BUILD_DIR

script:
  npm run ci:test

before_deploy:
  npm run build

deploy:
  provider: pages
  local_dir: _output
  skip_cleanup: true    # this does NOT git-stash (for cleaning up) before deploying
  name: Auto Deploy through Travis
  target_branch: gh-pages
  token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  strategy: git
  on:
    branch: master
